# Generated by Django 4.0.4 on 2022-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'data_table',
            },
        ),
    ]
