# Generated by Django 4.0.4 on 2022-05-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='uname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
